### ISSUE TITLE
The meaning seems to lie in renaming existing work, even almost cloning existing codebase. Directly undermining the double-blind rule of conference submissions

### ISSUE THREAD

**Issue by TinyYolo** [QgZhan/ESVAE#1]
I've browsed this repo and the corresponding arXiv. It seems like a manuscript of a course assignment level. The entire work can be regarded as an ablation experiment.

It is also a very confusing to disclose their submission status, before the reviewing stage.

**Comment by QgZhan** [comment]
In this work, we explored and found that SNN VAE is robust to the spike order of the latent vector, and accordingly proposed a simpler and more direct sampling method. 

Thank you for reminding us that we have hidden the submission status of this work.
